
pipeline:
  docker:
    image: plugins/docker
    repo: docker.stackdot.com/personal/qrpike
    tag:
      - '${DRONE_BRANCH/master/latest}'
      - '${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}'
    storage_driver: overlay
    when:
      branch: master

  deploy:
    image: vallard/drone-kube
    template: kube.yml
    namespace: personal
    when:
      branch: master