// Generated by CoffeeScript 1.6.3
var app;

app = angular.module('app', []);

app.controller('SimpleController', function($scope) {
  $scope.list = ['Get Money', 'Fuck Bitches', 'Be a Rapper'];
  $scope.addItem = function() {
    $scope.list.push($scope.newItem);
    return $scope.newItem = '';
  };
  return $scope.removeItem = function(item) {
    return $scope.list.splice($scope.list.indexOf(item), 1);
  };
});
