// Generated by CoffeeScript 1.6.3
var _APP;

_APP = null;

require(["main"], function(Main) {
  if (typeof console !== "undefined" && console !== null) {
    if (typeof console.log === "function") {
      console.log("Require JS Booted.");
    }
  }
  return _APP = new Main();
});
