// Generated by CoffeeScript 1.6.3
var app;

app = angular.module('app', []);

app.config(function($routeProvider) {
  $routeProvider.when('/meme/:url/:text', {
    templateUrl: 'view/meme.html',
    controller: 'MemeLoader'
  });
  $routeProvider.when('/', {
    templateUrl: 'view/create.html',
    controller: 'CreateMeme'
  });
  return $routeProvider.otherwise('/');
});

app.controller('MemeLoader', function($scope, $routeParams, $timeout) {
  $scope.meme = {
    image: decodeURIComponent($routeParams.url),
    text: decodeURIComponent($routeParams.text)
  };
  $scope.show = false;
  return $scope.showText = function() {
    return $timeout(function() {
      return $scope.show = true;
    }, 5000);
  };
});

app.controller('CreateMeme', function($scope, $location) {
  $scope.createMeme = function() {
    return $location.path("/meme/" + (encodeURIComponent($scope.newItem.image)) + "/" + (encodeURIComponent($scope.newItem.text)));
  };
  return $scope.removeItem = function(item) {
    return $scope.list.splice($scope.list.indexOf(item), 1);
  };
});
